### DISCUSSION TITLE
Export Limit or Power Limit control possible through RS485?

### DISCUSSION THREAD

**Discussion by Sven177** [syssi/esphome-modbus-solax-x1#59] [Q&A] [answered]
Hi Guys,
I am running a Solax X1-Mini and successfully made the RS485 interface sending the data to Home Assistant through an ESP32 and some according TTL converter Board. The Code provided here worked like a charm - thanks to all involved for that :-)

Now that I have kind of live data at hand, the next big thing would be either controlling the Inverter´s Export Limit or it´s Power Limit, using an existing sensor that is already present in Home Assistant. I don´t have a Smart Meter that would take that task (the Inverter is a bit further away from the electrical cabinet in the garage, feeding just 1 phase), but I am running a Shelly 3EM energy monitor, that is monitoring all 3 phases - and of course some "overal power" entity in Home Assistant, that will tell the direction (negative when exporting to the grid) as well as the Wattage.

So my question: would it be possible to kind of "emulate" the smart meter on the RS485 connection, to control the power output of the Inverter based on the measurement of the Shelly Energy Monitor?

I´m not a professional programmer (not by far), but would be thankful for some answers, hints, examples or other tips into the right direction...  ;-)

Thanks & Regards
Sven

**Comment by syssi** [comment]
The `esp8266-meter-gateway.yaml` of this project does exactly this. A MQTT topic is consumed to retrieve the power demand.

Please be aware of one important thing: You can either monitor the inverter using RS485 or control the output power. You cannot have both simultaneously because the operation mode of the RS485 port must be changed.

**Comment by Sven177** [comment]
Hi Syssi,

thanks for your fast reply. OK, that wouldn´t be too dramatic, since I still have some other methods of retreiving data (cloud service, WiFi Switches for measuring etc).
I actually saw that code snippet as well, but I wasn´t able to figure out how to "set" the according entity, that will tell the Inverter what power output it should set. Also I am definitely a noob regarding those MQTT functions (having only WMBusMeter configured to check the water meter).
So I guess I need to have the Shelly Entity for the overall power somehow as this MQTT source for this code?
And also I think the Inverter has to be set to a certain export limit as well afterwards - correct?
For I know when there is no meter connected, enabling the export control function will result in a "meter fault" error...

Regards and a nice evening!

**Reply by syssi** [reply]
Is the overall power consumption passed to Home Assistant and available as sensor entity here? I could provide a YAML snippet to retrieve the sensor measurement of the HA entity using the native `api`. In this case no MQTT is needed anymore.

As soon the power consumption is passed to the ESPHome node the measurement is converted into a power demand and passed using RS485/Modbus to the inverter (in export control meter). This will resolve the "meter fault" and the inverter will start to work + tries to produce the required power if available.

**Reply by Sven177** [reply]
Hi,

yes - the overall power consumption is already available in Home Assistant as a sensor (using the Shelly Integration).
I also have an ESP Board  with a display, that reads the sensor value from Home Assistant and shows it on the display, having that piece of code to get the sensor:

```
sensor:
  - platform: homeassistant
    id: Energiestatus
    entity_id: sensor.shelly_gesamt
```

Would be very nice if that MQTT function wouldn´t even be even needed to pass on this sensor value to the Meter-Gateway code then...  :-)

**Reply by syssi** [reply]
Just remove the MQTT sensor and add your sensor imported from Home Assistant:

Remove these lines: https://github.com/syssi/esphome-solax-x1-mini/blob/main/esp8266-meter-gateway.yaml#L64-L71

Add these (at the `sensor` section):

```
  - platform: homeassistant
    id: powermeter0
    entity_id: sensor.shelly_gesamt
    internal: true
    # It's important the unit of measurement is `W` here. If you use `kW` we should multiply the value using a filter.
```

The identifier `powermeter0` is important because the component `solax_meter_gateway` consumes this sensor here:

https://github.com/syssi/esphome-solax-x1-mini/blob/main/esp8266-meter-gateway.yaml#L59

**Reply by Sven177** [reply]
Awesome - thanks.
I will give it a try and get back to you... :-)

**Reply by Sven177** [reply]
Hi,

having the 3 entities available form the ESP Board (Emergency Switch, Operation Mode and Power demand)
Operation Mode and Power Demand shown as "unknown" - when checking the ESP Logs, it´s receiving the data of the Shelly Sensor as intended.
And I can see it´s handing over data to the powermeter0 sensor as well:
[10:35:15][D][sensor:094]: 'powermeter0': Sending state -35.65000  with 1 decimals of accuracy

Was enabling Export Control on the Inverter to see if Power Demand would change then, but then the Meter Gateway Operation Mode switched to "Meter Fault" causing the Inverter to go idle - so I disabled it again.

Am I missing something? Feels like almost there, with one tiny thing missing...

**Reply by syssi** [reply]
I guess the `power_sensor_inactivity_timeout` kicks in because your power meter doesn't provide an update per 5 seconds. Please increase the update interval of you powermeter if possible or increase the timeout:

https://github.com/syssi/esphome-solax-x1-mini/blob/main/esp8266-meter-gateway.yaml#L60C3-L60C34

**Reply by Sven177** [reply]
OK - thanks for your feedback and suggestion :-)
I will try...

**Reply by Sven177** [reply]
Hmmm,

changed the timeout for testing purpose to 20s, but still the same. The power demand and the operation status are shown as "unknown" when checking them at some entity card. The Energy Monitor should provide data with a sufficient timing, when checking the Log output of the board:

_[11:21:12][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 243.64
[11:21:12][D][sensor:094]: 'powermeter0': Sending state 243.64000  with 1 decimals of accuracy
[11:21:12][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 248.26
[11:21:12][D][sensor:094]: 'powermeter0': Sending state 248.25999  with 1 decimals of accuracy
[11:21:12][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 250.47
[11:21:12][D][sensor:094]: 'powermeter0': Sending state 250.47000  with 1 decimals of accuracy
[11:21:13][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 250.79
[11:21:13][D][sensor:094]: 'powermeter0': Sending state 250.78999  with 1 decimals of accuracy
[11:21:13][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 239.55
[11:21:13][D][sensor:094]: 'powermeter0': Sending state 239.55000  with 1 decimals of accuracy
[11:21:13][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 242.95
[11:21:13][D][sensor:094]: 'powermeter0': Sending state 242.95000  with 1 decimals of accuracy
[11:21:15][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 242.71
[11:21:15][D][sensor:094]: 'powermeter0': Sending state 242.71001  with 1 decimals of accuracy
[11:21:15][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 228.90
[11:21:15][D][sensor:094]: 'powermeter0': Sending state 228.89999  with 1 decimals of accuracy
[11:21:15][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 225.85
[11:21:15][D][sensor:094]: 'powermeter0': Sending state 225.85001  with 1 decimals of accuracy
[11:21:16][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 226.02
[11:21:16][D][sensor:094]: 'powermeter0': Sending state 226.02000  with 1 decimals of accuracy
[11:21:16][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 250.14
[11:21:16][D][sensor:094]: 'powermeter0': Sending state 250.14000  with 1 decimals of accuracy
[11:21:16][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 248.63
[11:21:16][D][sensor:094]: 'powermeter0': Sending state 248.63000  with 1 decimals of accuracy
[11:21:18][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 249.33
[11:21:18][D][sensor:094]: 'powermeter0': Sending state 249.33000  with 1 decimals of accuracy
[11:21:18][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 248.17
[11:21:18][D][sensor:094]: 'powermeter0': Sending state 248.17000  with 1 decimals of accuracy
[11:21:18][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 249.55
[11:21:18][D][sensor:094]: 'powermeter0': Sending state 249.55000  with 1 decimals of accuracy
[11:21:20][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 249.08
[11:21:20][D][sensor:094]: 'powermeter0': Sending state 249.08000  with 1 decimals of accuracy
[11:21:20][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 239.28
[11:21:20][D][sensor:094]: 'powermeter0': Sending state 239.28000  with 1 decimals of accuracy
[11:21:20][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 241.54
[11:21:20][D][sensor:094]: 'powermeter0': Sending state 241.53999  with 1 decimals of accuracy
[11:21:21][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 240.70
[11:21:21][D][sensor:094]: 'powermeter0': Sending state 240.70000  with 1 decimals of accuracy
[11:21:21][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 225.50
[11:21:21][D][sensor:094]: 'powermeter0': Sending state 225.50000  with 1 decimals of accuracy
[11:21:21][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 226.64
[11:21:21][D][sensor:094]: 'powermeter0': Sending state 226.64000  with 1 decimals of accuracy
[11:21:23][D][homeassistant.sensor:024]: 'sensor.shelly_gesamt': Got state 229.26_

What else could cause that issue? For it seems the powermeter0 should have the data it needs before timing out... 🤔

**Reply by syssi** [reply]
Could you provide some more logs (including the start-up) and your YAML configuration? The component should explain pretty early what's going on. I guess the `id: powermeter0` line is missing at the YAML.

**Reply by Sven177** [reply]
Hi,

sure. the Config.yaml file is divided into different !include sections, to not end up in a file that gets too big

```
# Loads default set of integrations. Do not remove.
default_config:
# Bluetooth
bluetooth:
# Text to speech
tts:
  - platform: google_translate
#--------------------------------------------------------------------------------------------------------  
my: http://192.168.178.118:8123
#--------------------------------------------------------------------------------------------------------
automation: !include automations.yaml
#--------------------------------------------------------------------------------------------------------
script: !include scripts.yaml
#--------------------------------------------------------------------------------------------------------
scene: !include scenes.yaml
#--------------------------------------------------------------------------------------------------------
switch: !include custom_switches.yaml
#--------------------------------------------------------------------------------------------------------
sensor: !include custom_sensors.yaml
#--------------------------------------------------------------------------------------------------------
utility_meter: !include custom_utility_meter.yaml
#--------------------------------------------------------------------------------------------------------
template: !include custom_templates.yaml
#--------------------------------------------------------------------------------------------------------
#Themes
lovelace:
  resources:
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /local/mini-graph-card-bundle.js?v=0.11.0
      type: module
    - url: /local/button-card.js
      type: module
frontend: 
  javascript_version: latest
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js
#---------------------------------------------------------------------------------------------------------
```

Do you mean the Log from the ESP Board or from Home Assistant?
