### ISSUE TITLE
Add flow control pin support

### ISSUE THREAD

**Issue by beocycris** [syssi/esphome-modbus-solax-x1#18]
Hey guys,

thank for this modules. In my case I try to use it with a Solax X1 mini 1.5 V2.
And I only receive the text which is mentioned in the title.
May anyone has the same issue and can help me to fix it.

regards
frank

**Comment by syssi** [comment]
Could you provide some details about your setup? A photo of your wiring (incl. the RS485 module) and the important parts (`uart` secontion) of your configuration yaml?

Another intepretation of the log message is: "The device doesn't respond". Therefore we must sure your device is connected properly. If this is the case it's possible your device version uses another protocol. Let's start with the wiring!

**Comment by beocycris** [comment]
I won´t be at home till friday - so I decided to do a small scheme of the cabling.

[solax_issue.pdf](https://github.com/syssi/esphome-modbus-solax-x1/files/8240550/solax_issue.pdf)


And the code too:

`
substitutions:
  name: solar-powermeter

esphome:
  name: ${name}
  platform: esp8266
  board: d1_mini

external_components:
  #- source: github://syssi/esphome-modbus-solax-x1@add-solax-x1-mini-g2-compatibility
  - source: github://syssi/esphome-modbus-solax-x1@main
    refresh: 0s

uart:
  baud_rate: 9600
  tx_pin: GPIO2
  rx_pin: GPIO1

solax_x1:
  serial_number: "3132333435363737363534333231"
  address: 0x0A
  update_interval: 2s

text_sensor:
  - platform: solax_x1
    mode_name:
      name: "${name} mode name"
    errors:
      name: "${name} errors"
`

thanks!

**Comment by syssi** [comment]
I assume your RS485 module isn't handled properly:

https://electronics.stackexchange.com/questions/153500/correctly-using-re-and-de-with-rs485

I will add a flow control pin to the component to support your rs485 module. At the moment DE/RE isn't used correctly.

**Comment by syssi** [comment]
I've introduce a flow control pin here:

https://github.com/syssi/esphome-modbus-solax-x1/pull/19

Please use this new feature branch for your tests:

```
external_components:
  - source: github://syssi/esphome-modbus-solax-x1@add-flow-control
    refresh: 0s
```

The next step is to update your configuration to use flow control pin:

https://github.com/syssi/esphome-modbus-solax-x1/pull/19/files#diff-dbc81de7d9fb76af6e67b9c8b02f69c8ea7f35b243a2898f26520c759e0d7b6d

This should fit for you

```
uart:
  id: uart0
  baud_rate: 9600
  tx_pin: GPIO2
  rx_pin: GPIO1

modbus_solax:
  id: modbus0
  uart_id: uart0
  flow_control_pin: GPIO2

solax_x1:
  modbus_solax_id: modbus0
  serial_number: "3132333435363737363534333231"
  address: 0x0A
  update_interval: 2s
```

**Comment by beocycris** [comment]
Do i have to change my wiring physically? Or may I can use the:
D1=GPIO4 as `tx` to the RS485-pin `RO`,
D2=GPIO5 as `rx` to the RS485-pin `DI` and 
GPIO0 as flowcontrole pin, connected to the bridged RS485-pins `RE/DE` ?

Or shell I change GPIO5 to the original `tx`-pin and the GPIO to the `rx`-pin on the microcrontroller?

Because I changed the my code to your provided one and nothing different happened than the issue above.

**Comment by syssi** [comment]
The `tx_pin` must connected to `DI` **not** `RI`. If you use `GPIO4` and `GPIO5` a software serial implementation is used by ESPHome. I would use the hardware UART pins of the ESP8266. The best wiring would look like this:

https://github.com/KlausLi/Esp-Soyosource-Controller/blob/main/BastelPlan3000_Soyosource_Controller_by_BavarianSuperGuy.png

```
api:
ota:
logger:
  level: INFO
  baud_rate: 0  # <--- super important!

uart:
  id: uart0
  baud_rate: 9600
  tx_pin: GPIO1
  rx_pin: GPIO3

modbus_solax:
  id: modbus0
  uart_id: uart0
  flow_control_pin: GPIO0

solax_x1:
  modbus_solax_id: modbus0
  serial_number: "3132333435363737363534333231"
  address: 0x0A
  update_interval: 2s
```
